<?xml version="1.0" encoding="utf-8"?><Database Name="cddss" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=54.93.154.67;Initial Catalog=cddss;Persist Security Info=True;User ID=cddss" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="AccessObject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="SecretQuestion" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="User_Rating" Member="Rating" ThisKey="Id" OtherKey="User" Type="Rating" />
      <Association Name="AccessObject_User" Member="AccessObject1" ThisKey="AccessObject" OtherKey="Id" Type="AccessObject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccessObject" Member="AccessObjects">
    <Type Name="AccessObject">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AccessObject_User" Member="Users" ThisKey="Id" OtherKey="AccessObject" Type="User" />
      <Association Name="AccessObject_AccessRight" Member="AccessRights" ThisKey="Id" OtherKey="AccessObject" Type="AccessRight" />
    </Type>
  </Table>
  <Table Name="dbo.AccessRight" Member="AccessRights">
    <Type Name="AccessRight">
      <Column Name="AccessObject" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Issue" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Right]" Member="Right" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="AccessObject_AccessRight" Member="AccessObject1" ThisKey="AccessObject" OtherKey="Id" Type="AccessObject" IsForeignKey="true" />
      <Association Name="Issue_AccessRight" Member="Issue1" ThisKey="Issue" OtherKey="Id" Type="Issue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Issue" Member="Issues">
    <Type Name="Issue">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="RelatedTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RelationType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ReviewRating" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Issue_AccessRight" Member="AccessRights" ThisKey="Id" OtherKey="Issue" Type="AccessRight" />
      <Association Name="Issue_Issue" Member="Issues" ThisKey="Id" OtherKey="RelatedTo" Type="Issue" />
      <Association Name="Issue_Document" Member="Documents" ThisKey="Id" OtherKey="Issue" Type="Document" />
      <Association Name="Issue_Criterion" Member="Criterion" ThisKey="Id" OtherKey="Issue" Type="Criterion" />
      <Association Name="Issue_Tag_Issue" Member="Tag_Issues" ThisKey="Id" OtherKey="Issue" Type="Tag_Issue" />
      <Association Name="Issue_Issue_artefact" Member="Issue_artefacts" ThisKey="Id" OtherKey="Issue" Type="Issue_artefact" />
      <Association Name="Issue_Issue_stakeholder" Member="Issue_stakeholders" ThisKey="Id" OtherKey="Issue" Type="Issue_stakeholder" />
      <Association Name="Issue_InfluenceFactor" Member="InfluenceFactors" ThisKey="Id" OtherKey="Issue" Type="InfluenceFactor" />
      <Association Name="Issue_Alternative" Member="Alternatives" ThisKey="Id" OtherKey="Issue" Type="Alternative" />
      <Association Name="Issue_Issue" Member="Issue1" ThisKey="RelatedTo" OtherKey="Id" Type="Issue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Document" Member="Documents">
    <Type Name="Document">
      <Column Name="Issue" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[File]" Member="File" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Issue_Document" Member="Issue1" ThisKey="Issue" OtherKey="Id" Type="Issue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Criterion" Member="Criterion">
    <Type Name="Criterion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Issue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Criterion_Rating" Member="Rating" ThisKey="Id" OtherKey="Criterion" Type="Rating" />
      <Association Name="Issue_Criterion" Member="Issue1" ThisKey="Issue" OtherKey="Id" Type="Issue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tag_Issue" Member="Tag_Issues">
    <Type Name="Tag_Issue">
      <Column Name="Tag" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Issue" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Issue_Tag_Issue" Member="Issue1" ThisKey="Issue" OtherKey="Id" Type="Issue" IsForeignKey="true" />
      <Association Name="Tag_Tag_Issue" Member="Tag1" ThisKey="Tag" OtherKey="Id" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tag" Member="Tags">
    <Type Name="Tag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Tag_Tag_Issue" Member="Tag_Issues" ThisKey="Id" OtherKey="Tag" Type="Tag_Issue" />
    </Type>
  </Table>
  <Table Name="dbo.Issue_artefact" Member="Issue_artefacts">
    <Type Name="Issue_artefact">
      <Column Name="Issue" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Artefact" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Issue_Issue_artefact" Member="Issue1" ThisKey="Issue" OtherKey="Id" Type="Issue" IsForeignKey="true" />
      <Association Name="Artefact_Issue_artefact" Member="Artefact1" ThisKey="Artefact" OtherKey="Id" Type="Artefact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Issue_stakeholder" Member="Issue_stakeholders">
    <Type Name="Issue_stakeholder">
      <Column Name="Issue" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Stakeholder" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Issue_Issue_stakeholder" Member="Issue1" ThisKey="Issue" OtherKey="Id" Type="Issue" IsForeignKey="true" />
      <Association Name="Stakeholder_Issue_stakeholder" Member="Stakeholder1" ThisKey="Stakeholder" OtherKey="Id" Type="Stakeholder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InfluenceFactor" Member="InfluenceFactors">
    <Type Name="InfluenceFactor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Characteristic" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Issue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Issue_InfluenceFactor" Member="Issue1" ThisKey="Issue" OtherKey="Id" Type="Issue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Artefact" Member="Artefacts">
    <Type Name="Artefact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Artefact_Issue_artefact" Member="Issue_artefacts" ThisKey="Id" OtherKey="Artefact" Type="Issue_artefact" />
    </Type>
  </Table>
  <Table Name="dbo.Stakeholder" Member="Stakeholders">
    <Type Name="Stakeholder">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Stakeholder_Issue_stakeholder" Member="Issue_stakeholders" ThisKey="Id" OtherKey="Stakeholder" Type="Issue_stakeholder" />
    </Type>
  </Table>
  <Table Name="dbo.Alternative" Member="Alternatives">
    <Type Name="Alternative">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Issue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Rating" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Alternative_Rating" Member="Rating1" ThisKey="Id" OtherKey="Alternative" Type="Rating" />
      <Association Name="Issue_Alternative" Member="Issue1" ThisKey="Issue" OtherKey="Id" Type="Issue" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rating" Member="Rating">
    <Type Name="Rating">
      <Column Name="Criterion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Alternative" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[User]" Member="User" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rating" Member="Rating1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Alternative_Rating" Member="Alternative1" ThisKey="Alternative" OtherKey="Id" Type="Alternative" IsForeignKey="true" />
      <Association Name="Criterion_Rating" Member="Criterion1" ThisKey="Criterion" OtherKey="Id" Type="Criterion" IsForeignKey="true" />
      <Association Name="User_Rating" Member="User1" ThisKey="User" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>